"""You are given an array of integers a.
A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
Your task is to determine whether the new array b is sorted in strictly ascending order or not."""


def solution(a):
    i, j = 0, len(a) - 1
    output = []
    while i < j:
        output.append(a[i])
        output.append(a[j])
        i += 1
        j -= 1
    if i == j:
        output.append(a[i])

    def is_increasing(numbers):
        for i in range(1, len(numbers)):
            if numbers[i] <= numbers[i - 1]:
                return False
        return True

    return is_increasing(output)


a = [1, 4, 5, 6, 3]
print(solution(a))
